### ISSUE TITLE
Inconsistent whitespace around comments?

### ISSUE THREAD

**Issue by RobLoach** [pantheon-systems/pantheon-edge-integrations#11]
I've found a few cases where the whitespace rules are not consistent, particularly around comments. Is this intentional?

![Screenshot at 2022-02-04 13-11-53](https://user-images.githubusercontent.com/25086/152581598-3aa7dffd-2365-4869-94e4-0923fde8e446.png)

**Comment by jazzsequence** [comment]
It's not intentional, it could be a tabbing thing. Does the `composer lint` output give more specific info (e.g. the sniff that's generating the error? It looks like the comments and the code they are commenting are in different columns, but I'm not positive if that's what the issue is.

**Comment by jazzsequence** [comment]
I've been looking at that file and I see some weird whitespace issues, so I think that's probably what the linter is reacting to.
