### ISSUE TITLE
Proposal: Switch default branch from `master` to `main`

### ISSUE THREAD

**Issue by jazzsequence** [pantheon-systems/pantheon-edge-integrations#5]
The `master` terminology is used mostly as a relic from the original source repository. However, there's no specific reason why it _has_ to be `master`. The new Drupal and WordPress SDK repositories, as well as the WordPress plugin repository, all use `main` as the default branch and it would be good to standardize.

@enotick @RobLoach Is there any specific reason to _not_ change the default branch to `main`? Would it affect anything in the `smart_content_cdn` module if the branch name changed to `main` there as well?

**Comment by enotick** [comment]
In this repo should be fine. In the Drupal, I believe Pantheon expects master since Pantheon Git uses master. So when we set it up we were just setting up both repos in the same way.

**Comment by jazzsequence** [comment]
> I believe Pantheon expects master since Pantheon Git uses master. 

That's definitely true for upstreams and project repositories, but I don't think that's true for individual modules. Drupal w/Composer wouldn't care about the branch name because it's pulling from whatever the tagged release would be, I'm not sure what other, non-Composer workflows might exist in Drupal-land, but I suspect that the branch name for the Smart Content CDN module wouldn't factor in.

I will set the default branch here to `main` at any rate and we can talk further about making that change (or not) in [`smart_content_cdn`](https://github.com/pantheon-systems/smart_content_cdn) later. (maybe tomorrow?)
